sudo: false

language: php

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.local
    - vendor

env:
  global:
    - COMPOSER_ARGS="--no-interaction"
    - COVERAGE_DEPS="satooshi/php-coveralls"
    - LEGACY_DEPS="phpunit/phpunit"

matrix:
  include:
    - php: 5.6
      env:
        - DEPS=lowest
    - php: 5.6
      env:
        - DEPS=locked
        - TEST_COVERAGE=true
    - php: 5.6
      env:
        - DEPS=latest
    - php: 7
      env:
        - DEPS=lowest
    - php: 7
      env:
        - DEPS=locked
        - CS_CHECK=true
    - php: 7
      env:
        - DEPS=latest
    - php: 7.1
      env:
        - DEPS=lowest
    - php: 7.1
      env:
        - DEPS=locked
    - php: 7.1
      env:
        - DEPS=latest
    - php: hhvm
      env:
        - DEPS=lowest
    - php: hhvm
      env:
        - DEPS=locked
    - php: hhvm
      env:
        - DEPS=latest
  allow_failures:
    - php: hhvm

before_install:
  - if [[ $TEST_COVERAGE != 'true' ]]; then phpenv config-rm xdebug.ini || return 0 ; fi
  - travis_retry composer self-update

install:
  - travis_retry composer install $COMPOSER_ARGS --ignore-platform-reqs
  - if [[ $TRAVIS_PHP_VERSION =~ ^5.6 ]]; then travis_retry composer update $COMPOSER_ARGS --with-dependencies $LEGACY_DEPS ; fi
  - if [[ $DEPS == 'latest' ]]; then travis_retry composer update $COMPOSER_ARGS ; fi
  - if [[ $DEPS == 'lowest' ]]; then travis_retry composer update --prefer-lowest --prefer-stable $COMPOSER_ARGS ; fi
  - if [[ $TEST_COVERAGE == 'true' ]]; then travis_retry composer require --dev $COMPOSER_ARGS $COVERAGE_DEPS ; fi
  - composer show

script:
  - if [[ $TEST_COVERAGE == 'true' ]]; then composer test-coverage ; else composer test ; fi
  - if [[ $CS_CHECK == 'true' ]]; then composer cs-check ; fi
  - if [[ $CS_CHECK == 'true' ]]; then composer license-check ; fi

after_script:
  - if [[ $TEST_COVERAGE == 'true' ]]; then composer upload-coverage ; fi

notifications:
  slack:
    secure: "AKzhI+UXy7hDxmfynkloa5xG3Dm13Pc976/IbPUSXHWi+qT9bDtCLpJ42YRW1SNTAD/FthprNSDkwM2MEF5z8+nA75Ahs+ZFHrDT1GWgu/AuRgDqCfBMbWZUNpqiwIN0FLyTF7owzwNZFHYsS8JykPelj1fOuYOhfUQebrz4ZsqTfYynclnppN4C6IhDRvANVxYpKIj7OEY6lL1rolXmz2BS+jGBC9fZZth67ge5SCs9t6j7r0EuoE4ng9i2pV5oEmNoz92AnXQ7HXtLhjME1oSbL5j+JpFFE7jz9AFJifzfDwT06RqOYGeS96S+Olcn8sHKTrQQp+dbvY5IpD0qEBiQFaJr9AYI+Rf5xHSAxvduPXmb3kKbMBudSf6kiLa+AwmC98ecVYp1TRZzuqKgBh3mGE3I/8hgVgxShyEae+aYRcpHtn0DnK3xCM96TvT8cKpZY/ziYhWpf79KBjj1mV4kErJdbnOqLGwtjPbi9YfsiOgz2sCFo75dBxzOhZscXGx9LY/WPJueJJzTnuzx89GxTnwhpKnBivU9yi2N0iVwV7Il0087/dr2H6uT4DpC4Rn3gSy11J1wyV4UAgJjjShhcu6zxiMf4stBFbnPFBVMhXPAYbGALP3dG8Wt//tKsS0tD9PwLgYojMvKYUbpOjSFk0b9WhrYIGdKfd00hOk="
  irc: "irc.freenode.org#zftalk.dev"
  email: false
